### PR TITLE
Better support for MMC3_198

### PR DESCRIPTION
**Pull request by RokkumanX**
Courtesy to @Rabenda

I took the liberty of polishing and tidying up the comments, otherwise it should work as intended.

### CODE REVIEW

**Comment by Rabenda** [comment]
https://github.com/SourMesen/Mesen/pull/555#issuecomment-450416868

Actually the comment is right. The ROM is mapper224.
But some nes which is mapper198 is masked wrongly.

**Comment by RokkumanX** [comment]
Thanks for the input @Rabenda !

So is there something wrong in the commit that needs to be changed or fixed?

A little backstory to all this would be that your pull request in the main Mesen repository came to my attention and I thought that it probably will be forever opened so I decided that I wanted to incorporate it in my own repository and here since this is the most up to date fork of Mesen.

I did a little research on it and thought it would be good to have so I made this.

Feel free to comment on this, because if there is something wrong I would like to know.

**Comment by caiqijie0** [comment]
Can you make Mapper 198 support 2MB

**Comment by caiqijie0** [comment]
value & 0x7F;     value & 0xfF;

**Pull request merged**
